# Generated by Django 4.2.5 on 2023-09-13 02:30

from django.db import migrations

import cities_light.abstract_models


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="search_names",
            field=cities_light.abstract_models.ToSearchTextField(
                blank=True,
                default="",
                max_length=4000,
                db_index=False,
            ),
        ),
    ]
